package sa;

public class JsonStructure {

	public static void main(String[] args) {
	

		String esnd=null;
		esnd="ESND";
		
		
		String val = "{\r\n" + "    \"ord\": {\r\n" + "        \"bussUnit\": \""+esnd+"\",\r\n"
				+ "        \"srcOrdNo\": \"ORDESND\",\r\n" + "        \"custOrdNo\": \"CUSTESND10152019123459\",\r\n"
				+ "        \"spltOrdNo\": \"9876543222\",\r\n" + "        \"ordNo\": \"\",\r\n"
				+ "        \"tranDt\": \"2019-09-21T16:16:10\",\r\n" + "        \"ordDt\": \"2019-09-21T16:16:10\",\r\n"
				+ "        \"ordTot\": \"999.99\",\r\n" + "        \"node\": \"085\",\r\n"
				+ "        \"splsNode\": \"972\",\r\n" + "        \"scac\": \"ABCDEF\",\r\n"
				+ "        \"scacCode\": \"GROUND\",\r\n" + "        \"hub\": \"3909\",\r\n"
				+ "        \"zone\": \"UP\",\r\n" + "        \"logoId\": \"11111111\",\r\n"
				+ "        \"shpLblId\": \"11111111\",\r\n" + "        \"snglLblReq\": \"N\",\r\n"
				+ "        \"pckLstReq\": \"Y\",\r\n" + "        \"reqShpDt\": \"2019-10-21T16:16:10\",\r\n"
				+ "        \"dlrRteTag\": \"11111\",\r\n" + "        \"dlrRte\": \"DLRRTE2345\",\r\n"
				+ "        \"dlrRefTag\": \"11111\",\r\n" + "        \"dlrRef\": \"DLRREF12345\",\r\n"
				+ "        \"dlrShrtRte\": \"DS001\",\r\n" + "        \"dlrMemoPO\": \"11vtl\",\r\n"
				+ "        \"endConPOTag\": \"epo\",\r\n" + "        \"endConPONum\": \"POBrderBridge\",\r\n"
				+ "        \"barCd1\": \"NJ001\",\r\n" + "        \"barCd2\": \"1001\",\r\n"
				+ "        \"barCd3\": \"DSROUTE\",\r\n" + "        \"barCd4\": \"Department001\",\r\n"
				+ "        \"ordLns\": {\r\n" + "            \"ordLn\": [\r\n" + "                {\r\n"
				+ "                    \"lnNo\": \"000000001\",\r\n"
				+ "                    \"rsrvId\": \"CUSTESND101520191234510\",\r\n"
				+ "                    \"ordQty\": \"5\",\r\n" + "                    \"rsrvdQty\": \"\",\r\n"
				+ "                    \"unitPrice\": \"9.99\",\r\n" + "                    \"lnPrice\": \"9.99\",\r\n"
				+ "                    \"srlNoReq\": \"Y\",\r\n" + "                    \"lnTxts\": {\r\n"
				+ "                        \"lnTxt\": [\r\n" + "                            {\r\n"
				+ "                                \"seqNo\": \"1\",\r\n"
				+ "                                \"lnTxtDesc\": \"this can have anything related to product of fields 81 characters\"\r\n"
				+ "                            },\r\n" + "                            {\r\n"
				+ "                                \"seqNo\": \"2\",\r\n"
				+ "                                \"lnTxtDesc\": \"this can have anything related to product of fields 81 characters\"\r\n"
				+ "                            }\r\n" + "                        ]\r\n" + "                    },\r\n"
				+ "                    \"item\": {\r\n" + "                        \"custSKU\": \"CUSTSKU123\",\r\n"
				+ "                        \"custUOM\": \"UM\",\r\n"
				+ "                        \"srcSKU\": \"ESD-192609\",\r\n"
				+ "                        \"srcUOM\": \"EA\",\r\n" + "                        \"splsSKU\": \"\",\r\n"
				+ "                        \"splsUOM\": \"\",\r\n"
				+ "                        \"skuDesc\": \"BINDER,DURIABLE,VW,5BK\",\r\n"
				+ "                        \"hazmatInd\": \"Y\"\r\n" + "                    }\r\n"
				+ "                }\r\n" + "            ]\r\n" + "        },\r\n" + "        \"insts\": {\r\n"
				+ "            \"inst\": [\r\n" + "                {\r\n"
				+ "                    \"type\": \"Dealer-Label\",\r\n"
				+ "                    \"txt1\": \"DEALER INSTRUCTION LINE1\",\r\n"
				+ "                    \"txt2\": \"DEALER INSTRUCTION LINE2\",\r\n"
				+ "                    \"txt3\": \"DEALER INSTRUCTION LINE3\",\r\n"
				+ "                    \"txt4\": \"DEALER INSTRUCTION LINE4\",\r\n"
				+ "                    \"txt5\": \"DEALER INSTRUCTION LINE5\",\r\n"
				+ "                    \"txt6\": \"DEALER INSTRUCTION LINE6\"\r\n" + "                },\r\n"
				+ "                {\r\n" + "                    \"type\": \"Dealer-PackList\",\r\n"
				+ "                    \"txt1\": \"Dealer-PackList INSTRUCTION LINE 1\",\r\n"
				+ "                    \"txt2\": \"Dealer-PackList INSTRUCTION LINE 2\",\r\n"
				+ "                    \"txt3\": \"Dealer-PackList INSTRUCTION LINE 3\",\r\n"
				+ "                    \"txt4\": \"Dealer-PackList INSTRUCTION LINE 4\",\r\n"
				+ "                    \"txt5\": \"Dealer-PackList INSTRUCTION LINE 5\",\r\n"
				+ "                    \"txt6\": \"Dealer-PackList INSTRUCTION LINE 6\"\r\n" + "                },\r\n"
				+ "                {\r\n" + "                    \"type\": \"Marketing-PackList\",\r\n"
				+ "                    \"txt1\": \"Marketing-PackList INSTRUCTION LINE 1\",\r\n"
				+ "                    \"txt2\": \"Marketing-PackList INSTRUCTION LINE 2\",\r\n"
				+ "                    \"txt3\": \"Marketing-PackList INSTRUCTION LINE 3\",\r\n"
				+ "                    \"txt4\": \"Marketing-PackList INSTRUCTION LINE 4\",\r\n"
				+ "                    \"txt5\": \"Marketing-PackList INSTRUCTION LINE 5\",\r\n"
				+ "                    \"txt6\": \"Marketing-PackList INSTRUCTION LINE 6\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"type\": \"Special-Label\",\r\n"
				+ "                    \"txt1\": \"Special-Label INSTRUCTION LINE 1\",\r\n"
				+ "                    \"txt2\": \"Special-Label INSTRUCTION LINE 2\",\r\n"
				+ "                    \"txt3\": \"Special-Label INSTRUCTION LINE 3\",\r\n"
				+ "                    \"txt4\": \"Special-Label INSTRUCTION LINE 4\",\r\n"
				+ "                    \"txt5\": \"Special-Label INSTRUCTION LINE 5\",\r\n"
				+ "                    \"txt6\": \"Special-Label INSTRUCTION LINE 6\"\r\n" + "                },\r\n"
				+ "                {\r\n" + "                    \"type\": \"Special-PackList\",\r\n"
				+ "                    \"txt1\": \"Special-PackList INSTRUCTION LINE 1\",\r\n"
				+ "                    \"txt2\": \"Special-PackList INSTRUCTION LINE 2\",\r\n"
				+ "                    \"txt3\": \"Special-PackList INSTRUCTION LINE 3\",\r\n"
				+ "                    \"txt4\": \"Special-PackList INSTRUCTION LINE 4\",\r\n"
				+ "                    \"txt5\": \"Special-PackList INSTRUCTION LINE 5\",\r\n"
				+ "                    \"txt6\": \"Special-PackList INSTRUCTION LINE 6\"\r\n" + "                },\r\n"
				+ "                {\r\n" + "                    \"type\": \"Return-PackList\",\r\n"
				+ "                    \"txt1\": \"Return-PackList INSTRUCTION LINE 1\",\r\n"
				+ "                                                                           \"txt2\": \"Return-PackList INSTRUCTION LINE 2\",\r\n"
				+ "                                                                           \"txt3\": \"Return-PackList INSTRUCTION LINE 3\",\r\n"
				+ "                                                                           \"txt4\": \"Return-PackList INSTRUCTION LINE 4\",\r\n"
				+ "                                                                           \"txt5\": \"Return-PackList INSTRUCTION LINE 5\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"type\": \"Miscl-PackList\",\r\n"
				+ "                                                                           \"txt1\": \"Miscl-PackList INSTRUCTION LINE 1\",\r\n"
				+ "                                                                           \"txt2\": \"Miscl-PackList INSTRUCTION LINE 2\",\r\n"
				+ "                                                                           \"txt3\": \"Miscl-PackList INSTRUCTION LINE 3\",\r\n"
				+ "                                                                           \"txt4\": \"Miscl-PackList INSTRUCTION LINE 4\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"type\": \"Single-Label\",\r\n"
				+ "                    \"txt1\": \"Single-Label INSTRUCTION LINE 1\",\r\n"
				+ "                                                                           \"txt2\": \"Single-Label INSTRUCTION LINE 2\",\r\n"
				+ "                                                                           \"txt3\": \"Single-Label INSTRUCTION LINE 3\",\r\n"
				+ "                                                                           \"txt4\": \"Single-Label INSTRUCTION LINE 4\",\r\n"
				+ "                                                                           \"txt5\": \"Single-Label INSTRUCTION LINE 5\",\r\n"
				+ "                                                                           \"txt6\": \"Single-Label INSTRUCTION LINE 6\"\r\n"
				+ "                }\r\n" + "            ]\r\n" + "        },\r\n" + "        \"addrLst\": {\r\n"
				+ "            \"addr\": [\r\n" + "                {\r\n"
				+ "                    \"type\": \"ShipTo\",\r\n"
				+ "                    \"name\": \"HiTouch Best Office Products Comp\",\r\n"
				+ "                    \"addLn1\": \"26 Boulder Run\",\r\n"
				+ "                    \"addLn2\": \"1st Floor\",\r\n"
				+ "                    \"city\": \"Oakland\",\r\n" + "                    \"state\": \"NJ\",\r\n"
				+ "                    \"zip\": \"074362352\",\r\n" + "                    \"country\": \"US\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "               \"type\": \"ShipFrom-PackList\",\r\n"
				+ "               \"name\": \"Essendand Edison Packlist\",\r\n"
				+ "               \"addLn1\": \"60 Saw Mill Pond RD\",\r\n"
				+ "               \"addLn2\": \"suite\",\r\n" + "               \"city\": \"Edison\",\r\n"
				+ "               \"state\": \"NJ\",\r\n" + "               \"zip\": \"08817\",\r\n"
				+ "               \"country\": \"US\"\r\n" + "            },\r\n" + "            {\r\n"
				+ "               \"type\": \"ShipFrom-Label\",\r\n"
				+ "               \"name\": \"Essendand Edison Label\",\r\n"
				+ "               \"addLn1\": \"60 Saw Mill Pond RD\",\r\n"
				+ "               \"addLn2\": \"suite\",\r\n" + "               \"city\": \"Edison\",\r\n"
				+ "               \"state\": \"NJ\",\r\n" + "               \"zip\": \"08817\",\r\n"
				+ "               \"country\": \"US\"\r\n" + "            },\r\n" + "            {\r\n"
				+ "               \"type\": \"Return\",\r\n"
				+ "               \"name\": \"Essendand Edison Return\",\r\n"
				+ "               \"addLn1\": \"60 Saw Mill Pond RD\",\r\n"
				+ "               \"addLn2\": \"suite\",\r\n" + "               \"city\": \"Edison\",\r\n"
				+ "               \"state\": \"NJ\",\r\n" + "               \"zip\": \"08817\",\r\n"
				+ "               \"country\": \"US\"\r\n" + "            }\r\n" + "            ]\r\n" + "        }\r\n"
				+ "    }\r\n" + "}\r\n" + "";
		
		
		
		System.out.println("Value:"+val);
		
		

	}

}
